import type { Response } from 'express';
import type { AuthenticatedRequest } from '../middlewares/auth';
import { GuildConfig } from '../../models/GuildConfig';
import { License } from '../../models/License';
import { User } from '../../models/User';
import { client as botClient } from '../../bot/client';
import { SystemMonitor } from '../../utils/systemMonitor';
import crypto from 'node:crypto';
export class AdminController {
 static async getMonitoring(_req:AuthenticatedRequest,res:Response){try{return res.json(await SystemMonitor.getStats());}catch{return res.status(500).json({error:'Échec de la collecte des métriques.'});}}
 static async togglePremium(req:AuthenticatedRequest,res:Response){try{const {guildId,isPremium,tier,durationInDays}=req.body||{};if(guildId==='USER_LICENSE'){const userId=String(req.body?.userId||req.user?.discordId||'');const user=await User.findOne({discordId:userId});if(!user)return res.status(404).json({error:'Utilisateur introuvable.'});await License.updateMany({buyerId:userId,status:'active'},{$set:{status:'suspended'}});if(isPremium){const days=Number(durationInDays);const expiresAt=days>0?new Date(Date.now()+days*86400000):null;await License.create({key:`OMNIX-USER-${crypto.randomBytes(10).toString('hex').toUpperCase()}`,tier:days===0?'lifetime':'premium',status:'active',buyerId:userId,activatedGuildId:null,activatedAt:null,expiresAt,durationInDays:days});user.isPremium=true;}else user.isPremium=false;await user.save();return res.json({message:'Licence utilisateur mise à jour.',user});}const id=String(guildId||'');if(!/^\d{17,20}$/.test(id))return res.status(400).json({error:'Guild ID invalide.'});const days=Number(durationInDays);const config=await GuildConfig.findOneAndUpdate({guildId:id},{$set:{'premium.isPremium':Boolean(isPremium),'premium.tier':isPremium?(days===0?'lifetime':tier||'premium'):'free','premium.expiresAt':isPremium&&days>0?new Date(Date.now()+days*86400000):null},$setOnInsert:{guildId:id}},{new:true,upsert:true,runValidators:true});return res.json({message:`Statut premium du serveur ${id} mis à jour.`,config});}catch(e:any){console.error('[Admin API] togglePremium',e);return res.status(500).json({error:'Impossible de modifier le statut.'});}}
 static async sendGlobalAnnouncement(req:AuthenticatedRequest,res:Response){const message=String(req.body?.messageContent||'').trim().slice(0,2000);if(!message)return res.status(400).json({error:'Le contenu du message est requis.'});let count=0;for(const guild of botClient.guilds.cache.values()){const ch=guild.systemChannel||guild.channels.cache.find(c=>c.isTextBased()&&guild.members.me&&c.permissionsFor(guild.members.me)?.has('SendMessages'));if(ch&&'send'in ch){await ch.send({content:`📢 **Annonce Globale OMNIX**\n\n${message}`}).catch(()=>null);count++;}}return res.json({message:`Annonce envoyée avec succès sur ${count} serveur(s).`});}
 static async getUsers(_req:AuthenticatedRequest,res:Response){try{return res.json(await User.find({}).select('-accessToken -refreshToken -tokenExpiresAt').sort({createdAt:-1}).lean());}catch{return res.status(500).json({error:'Impossible de récupérer la liste.'});}}
 static async toggleBlacklist(req:AuthenticatedRequest,res:Response){const id=String(req.body?.userId||'');const flag=Boolean(req.body?.isBlacklisted);const user=await User.findOne({discordId:id});if(!user)return res.status(404).json({error:'Utilisateur introuvable.'});if(user.isAdmin&&flag)return res.status(400).json({error:'Impossible de bannir un membre du staff.'});user.isBlacklisted=flag;await user.save();return res.json({message:'Statut de bannissement mis à jour.',user});}
}
