import type { Response } from 'express';
import type { AuthenticatedRequest } from '../middlewares/auth';
import { GuildConfig } from '../../models/GuildConfig';
function flatten(value:any,prefix=''):Record<string,unknown>{const out:Record<string,unknown>={};if(!value||typeof value!=='object'||Array.isArray(value))return out;for(const key of Object.keys(value)){const item=value[key],next=prefix?`${prefix}${key}`:key;if(item&&typeof item==='object'&&!Array.isArray(item)&&!(item instanceof Date))Object.assign(out,flatten(item,`${next}.`));else out[next]=item;}return out;}
function reserved(key:string){return ['guildId','_id','__v','createdAt','updatedAt','premium'].some(x=>key===x||key.startsWith(`${x}.`))||key.split('.').some(x=>x.startsWith('$'));}
export class GuildConfigController {
 static async getConfig(req:AuthenticatedRequest,res:Response){const guildId=String(req.params.guildId||'').trim();if(!/^\d{17,20}$/.test(guildId))return res.status(400).json({success:false,error:'Identifiant de serveur invalide.'});try{let config=await GuildConfig.findOne({guildId});if(!config){config=new GuildConfig({guildId});await config.save();}return res.json(config);}catch(e){console.error('[Config API] GET',e);return res.status(500).json({success:false,error:'Erreur lors de la récupération de la configuration.'});}}
 static async updateConfig(req:AuthenticatedRequest,res:Response){const guildId=String(req.params.guildId||'').trim();if(!/^\d{17,20}$/.test(guildId))return res.status(400).json({success:false,error:'Identifiant de serveur invalide.'});try{const updates=Object.fromEntries(Object.entries(flatten(req.body||{})).filter(([k])=>!reserved(k)));if(!Object.keys(updates).length)return res.status(400).json({success:false,error:'Aucun paramètre modifiable fourni.'});const config=await GuildConfig.findOneAndUpdate({guildId},{$set:updates},{new:true,runValidators:true});if(!config)return res.status(404).json({success:false,error:'Configuration introuvable.'});return res.json({success:true,message:'Paramètres enregistrés.',config});}catch(e){console.error('[Config API] PUT',e);return res.status(400).json({success:false,error:'Données de configuration non conformes.'});}}
}
