import type { Request, Response } from 'express';
import Stripe from 'stripe';
import crypto from 'node:crypto';
import { CONFIG } from '../../config/index';
import { License } from '../../models/License';
import { PricingOffer } from '../../models/PricingOffer';
import type { AuthenticatedRequest } from '../middlewares/auth';
const stripe = CONFIG.PAYMENTS.STRIPE_SECRET_KEY.trim() ? new Stripe(CONFIG.PAYMENTS.STRIPE_SECRET_KEY.trim(), { apiVersion: '2025-01-27' as any }) : null;
const str=(v:unknown,n=100)=>typeof v==='string'?v.trim().slice(0,n):'';
export class PaymentController {
 static async createCheckoutSession(req:AuthenticatedRequest,res:Response){const u=req.user;if(!u?.discordId)return res.status(401).json({success:false,error:'Identification requise.'});const priceId=str(req.body?.priceId);const tier=str(req.body?.tier,30);const days=Number(req.body?.durationInDays);if(!/^price_[A-Za-z0-9]+$/.test(priceId)||!['premium','lifetime','enterprise'].includes(tier)||!Number.isInteger(days)||days<0||days>3650)return res.status(400).json({success:false,error:'Offre de paiement invalide.'});try{if(!stripe)throw new Error('Stripe non configuré.');const price=await stripe.prices.retrieve(priceId,{expand:['product']});if(!price.active)return res.status(400).json({success:false,error:'Offre Stripe inactive.'});const catalog=await PricingOffer.findOne({active:true,stripePriceId:priceId}).lean().catch(()=>null);if(catalog&&Number(catalog.durationDays)!==days)return res.status(400).json({success:false,error:'Durée d’offre invalide.'});const origin=CONFIG.CLIENT_URL||CONFIG.DOMAIN;if(!origin)throw new Error('CLIENT_URL/DOMAIN non configuré.');const mode=price.type==='recurring'?'subscription':'payment';const session=await stripe.checkout.sessions.create({payment_method_types:['card'],line_items:[{price:priceId,quantity:1}],mode,metadata:{userId:u.discordId,tier,durationInDays:String(days),priceId},success_url:`${origin}/dashboard?payment=success`,cancel_url:`${origin}/dashboard?payment=cancel`});return res.json({success:true,id:session.id,url:session.url});}catch(e:any){console.error('[Stripe] Checkout:',e?.message||e);return res.status(500).json({success:false,error:'Création de la session de paiement impossible.'});}}
 static async handleWebhook(req:Request & {rawBody?:Buffer},res:Response){const sig=req.headers['stripe-signature'];if(!sig)return res.status(400).send('Signature Stripe manquante.');if(!stripe||!CONFIG.PAYMENTS.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Webhook Stripe non configuré.');try{const raw=req.rawBody??(Buffer.isBuffer(req.body)?req.body:null);if(!raw)return res.status(400).send('Corps brut Stripe indisponible.');const event=stripe.webhooks.constructEvent(raw,sig,CONFIG.PAYMENTS.STRIPE_WEBHOOK_SECRET);if(event.type==='checkout.session.completed'){const session=event.data.object as Stripe.Checkout.Session;const buyer=str(session.metadata?.userId,32);const tier=str(session.metadata?.tier,30);const days=Number(session.metadata?.durationInDays??30);if(!/^\d{17,20}$/.test(buyer)||!['premium','lifetime','enterprise'].includes(tier)||!Number.isInteger(days)||days<0||days>3650)return res.status(400).send('Métadonnées invalides.');const exists=await License.findOne({$or:[{stripeSessionId:session.id},{stripeEventId:event.id}]});if(!exists){const a=crypto.randomBytes(8).toString('hex').toUpperCase(),b=crypto.randomBytes(4).toString('hex').toUpperCase();try{await License.create({key:`OMNIX-${a.slice(0,4)}-${a.slice(4,8)}-${b}`,tier,status:'active',buyerId:buyer,durationInDays:days,expiresAt:days>0?new Date(Date.now()+days*86400000):null,stripeSessionId:session.id,stripeEventId:event.id});}catch(e:any){if(e?.code!==11000)throw e;}}}return res.json({received:true});}catch(e:any){console.error('[Stripe] Webhook:',e?.message||e);return res.status(400).send('Signature Webhook invalide.');}}
}
