export const OMNIX_MODULES = [
  { key:'moderation', category:'Modération', label:'Modération', premium:false },
  { key:'autoMod', category:'Sécurité', label:'AutoMod', premium:false },
  { key:'antiRaid', category:'Sécurité', label:'Anti-Raid', premium:false },
  { key:'security', category:'Sécurité', label:'Security Center', premium:false },
  { key:'welcome', category:'Communauté', label:'Welcome / Goodbye', premium:false },
  { key:'autoRole', category:'Communauté', label:'Auto-Roles', premium:false },
  { key:'reactionRoles', category:'Communauté', label:'Reaction Roles', premium:false },
  { key:'suggestions', category:'Communauté', label:'Suggestions', premium:false },
  { key:'polls', category:'Communauté', label:'Sondages', premium:false },
  { key:'levels', category:'Engagement', label:'Levels / XP', premium:false },
  { key:'tickets', category:'Support', label:'Tickets', premium:false },
  { key:'logs', category:'Observabilité', label:'Logs', premium:false },
  { key:'statistics', category:'Observabilité', label:'Analytics', premium:false },
  { key:'economy', category:'Économie virtuelle', label:'Economy', premium:false },
  { key:'ai', category:'IA', label:'Omnix AI', premium:true },
  { key:'backups', category:'Continuité', label:'Backups', premium:true },
  { key:'customCommands', category:'Automatisation', label:'Custom Commands', premium:false },
  { key:'verification', category:'Sécurité', label:'Verification', premium:false },
  { key:'honeypot', category:'Sécurité', label:'Honeypot', premium:true },
] as const;
export type OmnixModuleKey = typeof OMNIX_MODULES[number]['key'];
